; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8_128k]
platform = ststm32
board = bluepill_f103c8_128k
framework = arduino

lib_deps = 
    bodmer/TFT_eSPI

; Настройки для загрузчика https://github.com/Serasidis/STM32_HID_Bootloader/releases/tag/2.2.2
upload_protocol = hid
;upload_port = ANY
;upload_port = COM7

; Смещение для загрузчика hid_generic_pc13.bin (2KB)
board_build.offset = 0x800 

build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    
    ; Настройки дисплея
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1        ; драйвер дисплея
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TOUCH_CS=-1            ; Тач отстутствует
    -D TFT_RGB_ORDER=TFT_BGR  ; Попробуем BGR (если цвета будут странные — сменим)
    -D TFT_INVERSION_ON       ; ST7789 часто требует инверсию цвета программно
    -D TFT_MOSI=PA7           ; SDA
    -D TFT_SCLK=PA5           ; SCL
    -D TFT_CS=PA4             ; CS
    -D TFT_DC=PA3             ; DC
    -D TFT_RST=PA2            ; RST
    ; -D TFT_BL=PB10            ; Подсветка
    ; -D TFT_BACKLIGHT_ON=HIGH  ; Включаем логической единицей
    -D LOAD_GLCD=1            ; Стандартный шрифт
    -D LOAD_FONT2=1           ; Мелкий
    -D LOAD_FONT4=1           ; Средний (для температуры)
    -D SPI_FREQUENCY=27000000 ; Частота SPI